services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/prisma/generated
      - /app/dist
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql://root:password@mysql:3306/interview_db
    depends_on:
      mysql:
        condition: service_healthy
    entrypoint: ["sh", "/app/docker-entrypoint.sh"]
    command: ["npm", "run", "start:dev"]

  mysql:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: interview_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: